services:
  # --- DEPOLAMA (MINIO) ---
  minio:
    image: minio/minio:latest
    container_name: datalake-minio
    ports: ["9000:9000", "9001:9001"]
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes: ["./minio_data:/data"]

  # --- İŞLEME (SPARK) ---
  spark:
    image: jupyter/pyspark-notebook:latest
    container_name: datalake-spark
    ports: ["8888:8888", "4040:4040"]
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=spark123
    volumes: ["./workspace:/home/jovyan/work"]

  # --- VERİTABANI (AIRFLOW METADATA) ---
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports: ["5432:5432"]

  # --- AIRFLOW WEB-SERVER & SCHEDULER ---
  airflow:
    image: apache/airflow:2.7.1-python3.10
    container_name: datalake-airflow
    depends_on:
      - postgres
    environment:
      - EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    
      - _AIRFLOW_DB_UPGRADE=True
      - _AIRFLOW_WWW_USER_CREATE=True
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    
    command: standalone
